// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilhasAPI.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MilhasAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260519213126_AddProgramToCardsAndTransactions")]
    partial class AddProgramToCardsAndTransactions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MilhasAPI.Models.CreditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Program")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CreditCards");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Brand = "Visa Infinite",
                            CardNumber = "**** **** **** 1234",
                            UserId = 100
                        },
                        new
                        {
                            Id = 101,
                            Brand = "Mastercard Black",
                            CardNumber = "**** **** **** 5678",
                            UserId = 100
                        },
                        new
                        {
                            Id = 102,
                            Brand = "Amex Platinum",
                            CardNumber = "**** **** **** 9012",
                            UserId = 101
                        },
                        new
                        {
                            Id = 103,
                            Brand = "Visa Platinum",
                            CardNumber = "**** **** **** 3456",
                            UserId = 101
                        },
                        new
                        {
                            Id = 104,
                            Brand = "Elo Nanquim",
                            CardNumber = "**** **** **** 7890",
                            UserId = 102
                        },
                        new
                        {
                            Id = 105,
                            Brand = "Mastercard Platinum",
                            CardNumber = "**** **** **** 2345",
                            UserId = 102
                        },
                        new
                        {
                            Id = 106,
                            Brand = "Visa Gold",
                            CardNumber = "**** **** **** 6789",
                            UserId = 103
                        },
                        new
                        {
                            Id = 107,
                            Brand = "Amex Gold",
                            CardNumber = "**** **** **** 0123",
                            UserId = 104
                        },
                        new
                        {
                            Id = 108,
                            Brand = "Mastercard Black",
                            CardNumber = "**** **** **** 4567",
                            UserId = 104
                        });
                });

            modelBuilder.Entity("MilhasAPI.Models.MilesGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetMiles")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MilesGoals");
                });

            modelBuilder.Entity("MilhasAPI.Models.RewardTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("CreditCardId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MilesEarned")
                        .HasColumnType("integer");

                    b.Property<int?>("Program")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("UserId");

                    b.ToTable("RewardTransactions");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Amount = 2500m,
                            CreditCardId = 100,
                            Date = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MilesEarned = 7500,
                            UserId = 100
                        },
                        new
                        {
                            Id = 101,
                            Amount = 3200m,
                            CreditCardId = 101,
                            Date = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            MilesEarned = 9600,
                            UserId = 100
                        },
                        new
                        {
                            Id = 102,
                            Amount = 8000m,
                            CreditCardId = 102,
                            Date = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            MilesEarned = 24000,
                            UserId = 101
                        },
                        new
                        {
                            Id = 103,
                            Amount = 5500m,
                            CreditCardId = 103,
                            Date = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            MilesEarned = 11000,
                            UserId = 101
                        },
                        new
                        {
                            Id = 104,
                            Amount = 1800m,
                            CreditCardId = 104,
                            Date = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            MilesEarned = 3600,
                            UserId = 102
                        },
                        new
                        {
                            Id = 105,
                            Amount = 900m,
                            CreditCardId = 106,
                            Date = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            MilesEarned = 1800,
                            UserId = 103
                        },
                        new
                        {
                            Id = 106,
                            Amount = 4200m,
                            CreditCardId = 107,
                            Date = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            MilesEarned = 12600,
                            UserId = 104
                        },
                        new
                        {
                            Id = 107,
                            Amount = 6100m,
                            CreditCardId = 108,
                            Date = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            MilesEarned = 18300,
                            UserId = 104
                        });
                });

            modelBuilder.Entity("MilhasAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Email = "ana.silva@email.com",
                            Name = "Ana Silva"
                        },
                        new
                        {
                            Id = 101,
                            Email = "carlos.mendes@email.com",
                            Name = "Carlos Mendes"
                        },
                        new
                        {
                            Id = 102,
                            Email = "beatriz.oliveira@email.com",
                            Name = "Beatriz Oliveira"
                        },
                        new
                        {
                            Id = 103,
                            Email = "rafael.costa@email.com",
                            Name = "Rafael Costa"
                        },
                        new
                        {
                            Id = 104,
                            Email = "juliana.santos@email.com",
                            Name = "Juliana Santos"
                        });
                });

            modelBuilder.Entity("MilhasAPI.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualCardFeeBudget")
                        .HasColumnType("numeric");

                    b.Property<int>("CurrentMilesBalance")
                        .HasColumnType("integer");

                    b.Property<bool>("InterestedInCardUpgrades")
                        .HasColumnType("boolean");

                    b.Property<bool>("InterestedInMilesTransferPromos")
                        .HasColumnType("boolean");

                    b.Property<int>("InvestmentProfile")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxMilePurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlyCardSpending")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("numeric");

                    b.Property<int>("MonthlyMilesGoal")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfCreditCards")
                        .HasColumnType("integer");

                    b.Property<int>("PreferredCabinClass")
                        .HasColumnType("integer");

                    b.Property<int>("PreferredLoyaltyProgram")
                        .HasColumnType("integer");

                    b.Property<bool>("PrefersDomesticTravel")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrefersInternationalTravel")
                        .HasColumnType("boolean");

                    b.Property<int>("TravelFrequency")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            AnnualCardFeeBudget = 1500m,
                            CurrentMilesBalance = 120000,
                            InterestedInCardUpgrades = true,
                            InterestedInMilesTransferPromos = true,
                            InvestmentProfile = 2,
                            MaxMilePurchasePrice = 22m,
                            MonthlyCardSpending = 8000m,
                            MonthlyIncome = 12000m,
                            MonthlyMilesGoal = 15000,
                            NumberOfCreditCards = 2,
                            PreferredCabinClass = 2,
                            PreferredLoyaltyProgram = 4,
                            PrefersDomesticTravel = true,
                            PrefersInternationalTravel = true,
                            TravelFrequency = 2,
                            UserId = 100
                        },
                        new
                        {
                            Id = 101,
                            AnnualCardFeeBudget = 3000m,
                            CurrentMilesBalance = 350000,
                            InterestedInCardUpgrades = true,
                            InterestedInMilesTransferPromos = true,
                            InvestmentProfile = 2,
                            MaxMilePurchasePrice = 30m,
                            MonthlyCardSpending = 18000m,
                            MonthlyIncome = 25000m,
                            MonthlyMilesGoal = 30000,
                            NumberOfCreditCards = 2,
                            PreferredCabinClass = 3,
                            PreferredLoyaltyProgram = 0,
                            PrefersDomesticTravel = false,
                            PrefersInternationalTravel = true,
                            TravelFrequency = 3,
                            UserId = 101
                        },
                        new
                        {
                            Id = 102,
                            AnnualCardFeeBudget = 600m,
                            CurrentMilesBalance = 45000,
                            InterestedInCardUpgrades = false,
                            InterestedInMilesTransferPromos = true,
                            InvestmentProfile = 1,
                            MaxMilePurchasePrice = 18m,
                            MonthlyCardSpending = 4000m,
                            MonthlyIncome = 7000m,
                            MonthlyMilesGoal = 8000,
                            NumberOfCreditCards = 2,
                            PreferredCabinClass = 1,
                            PreferredLoyaltyProgram = 2,
                            PrefersDomesticTravel = true,
                            PrefersInternationalTravel = false,
                            TravelFrequency = 1,
                            UserId = 102
                        },
                        new
                        {
                            Id = 103,
                            AnnualCardFeeBudget = 0m,
                            CurrentMilesBalance = 8000,
                            InterestedInCardUpgrades = false,
                            InterestedInMilesTransferPromos = false,
                            InvestmentProfile = 0,
                            MaxMilePurchasePrice = 12m,
                            MonthlyCardSpending = 2500m,
                            MonthlyIncome = 4500m,
                            MonthlyMilesGoal = 3000,
                            NumberOfCreditCards = 1,
                            PreferredCabinClass = 0,
                            PreferredLoyaltyProgram = 1,
                            PrefersDomesticTravel = true,
                            PrefersInternationalTravel = false,
                            TravelFrequency = 0,
                            UserId = 103
                        },
                        new
                        {
                            Id = 104,
                            AnnualCardFeeBudget = 2000m,
                            CurrentMilesBalance = 200000,
                            InterestedInCardUpgrades = true,
                            InterestedInMilesTransferPromos = true,
                            InvestmentProfile = 1,
                            MaxMilePurchasePrice = 25m,
                            MonthlyCardSpending = 10000m,
                            MonthlyIncome = 15000m,
                            MonthlyMilesGoal = 20000,
                            NumberOfCreditCards = 2,
                            PreferredCabinClass = 2,
                            PreferredLoyaltyProgram = 5,
                            PrefersDomesticTravel = true,
                            PrefersInternationalTravel = true,
                            TravelFrequency = 2,
                            UserId = 104
                        });
                });

            modelBuilder.Entity("MilhasAPI.Models.CreditCard", b =>
                {
                    b.HasOne("MilhasAPI.Models.User", "User")
                        .WithMany("CreditCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MilhasAPI.Models.MilesGoal", b =>
                {
                    b.HasOne("MilhasAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MilhasAPI.Models.RewardTransaction", b =>
                {
                    b.HasOne("MilhasAPI.Models.CreditCard", "CreditCard")
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilhasAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MilhasAPI.Models.UserProfile", b =>
                {
                    b.HasOne("MilhasAPI.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("MilhasAPI.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MilhasAPI.Models.User", b =>
                {
                    b.Navigation("CreditCards");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
