// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MilhasAPI.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MilhasAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MilhasAPI.Models.CreditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CreditCards", (string)null);
                });

            modelBuilder.Entity("MilhasAPI.Models.RewardTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("CreditCardId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MilesEarned")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreditCardId");

                    b.HasIndex("UserId");

                    b.ToTable("RewardTransactions", (string)null);
                });

            modelBuilder.Entity("MilhasAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MilhasAPI.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualCardFeeBudget")
                        .HasColumnType("numeric");

                    b.Property<int>("CurrentMilesBalance")
                        .HasColumnType("integer");

                    b.Property<bool>("InterestedInCardUpgrades")
                        .HasColumnType("boolean");

                    b.Property<bool>("InterestedInMilesTransferPromos")
                        .HasColumnType("boolean");

                    b.Property<int>("InvestmentProfile")
                        .HasColumnType("integer");

                    b.Property<decimal>("MaxMilePurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlyCardSpending")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("numeric");

                    b.Property<int>("MonthlyMilesGoal")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfCreditCards")
                        .HasColumnType("integer");

                    b.Property<int>("PreferredCabinClass")
                        .HasColumnType("integer");

                    b.Property<int>("PreferredLoyaltyProgram")
                        .HasColumnType("integer");

                    b.Property<bool>("PrefersDomesticTravel")
                        .HasColumnType("boolean");

                    b.Property<bool>("PrefersInternationalTravel")
                        .HasColumnType("boolean");

                    b.Property<int>("TravelFrequency")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("MilhasAPI.Models.CreditCard", b =>
                {
                    b.HasOne("MilhasAPI.Models.User", null)
                        .WithMany("CreditCards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MilhasAPI.Models.RewardTransaction", b =>
                {
                    b.HasOne("MilhasAPI.Models.CreditCard", "CreditCard")
                        .WithMany()
                        .HasForeignKey("CreditCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MilhasAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MilhasAPI.Models.UserProfile", b =>
                {
                    b.HasOne("MilhasAPI.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("MilhasAPI.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MilhasAPI.Models.User", b =>
                {
                    b.Navigation("CreditCards");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
